api:
  image:
    repository: ghcr.io/joshwavetti/trailapi
    tag: v4
  port: 8080

frontend:
  image:
    repository: ghcr.io/joshwavetti/frontend
    tag: v5
  port: 80

postgres:
  image: postgres:16
  database: trailconditions
  username: postgres
  password: postgres